name: Generate Documentation
on:
  workflow_dispatch:

jobs:
  use-reusable-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    uses: ingka-group-digital/code-to-docs/.github/workflows/reusable-workflow.yml@0.0.2
    with:
      src-folder: src
      repo-name: ${{ github.repository }}
      branch-name: main
      token: ${{ secrets.PAT_TOKEN  }}
