name: Auto-Generate Docs with Copilot
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**/*.kt"  # Run when Kotlin files change

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Documentation with Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Store token in GitHub Secrets
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY_PR }}  # Pass the secret to the script
        run: python generate_docs.py
      - name: Commit and push changes to Caller repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add . # Add modified files
          git commit -m "Auto-generated documentation with GitHub Copilot"
          git push