name: Auto-Generate Docs with Copilot
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**/*.kt"  # Run when Kotlin files change

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Documentation with Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Store token in GitHub Secrets
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY_PR }}  # Pass the secret to the script
        run: python generate_docs.py
      - name: Commit and push changes to Caller repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b update-caller-repo-files-${GITHUB_SHA}-${GITHUB_RUN_NUMBER} # Create a new branch for changes
          git add . # Add modified files
          git commit -m "Auto-generated documentation using AI"
          git push --set-upstream origin update-caller-repo-files-${GITHUB_SHA}-${GITHUB_RUN_NUMBER} # Push the new branch to Repository

      - name: Create Pull Request in Caller repository
        run: |
            curl -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -d '{
                  "title": "Update files in src folder",
                  "head": "update-caller-repo-files-${GITHUB_SHA}-${GITHUB_RUN_NUMBER}",
                  "base": "main",
                  "body": "Automated pull request to update files in src folder from script."
                }' \
            https://api.github.com/repos/shrabdut123/testSemRepo/pulls