name: "Rotate Admin JFrog Token"

on:
  schedule:
    - cron: "0 0 30 * *"
  workflow_dispatch:
    inputs:
      EXPIRY_IN_SECONDS:
        type: string
        required: false
        default: "3024000" # 35 days in seconds
        description: Defaults to 85 days. Set it if you are using a different duration.
      JF_PLATFORM_URL:
        type: string
        required: false
        default: "https://artifactory.build.ingka.ikea.com/"
        description: Defaults to current production value. Set it if you are using a different Artifactory setup, like staging.        
        

jobs:
  rotate-jfrog-token-in-gh-secret:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.set-output.outputs.UPDATED_ACCESS_TOKEN }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Make a POST request using curl
        id: step1
        run: |
          response=$(curl "https://artifactory.build.ingka.ikea.com/access/api/v1/tokens" -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_TEST_TOKEN }}" -H "Content-Type: application/json" -X POST -d '{"refreshable": true,"expires_in": 86400 }')
          echo "access_token=$(echo $response | jq -r '.access_token')"
      - name: Encode a username&token to Base64
        id: encode-username-token
        run: |
          echo "ARTIFACTORY_TEST_USERNAME : ${{ vars.ARTIFACTORY_TEST_USERNAME }}"
          echo "Access token: ${{ steps.step1.outputs.access_token }}"
          echo "username_token=$(echo -n "${{ vars.ARTIFACTORY_TEST_USERNAME }}:${{ steps.step1.outputs.access_token }}" | base64)"
          echo "Encoded secret: $username_token"
      - name: Update new token in Github actions secret
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash --norc -eo pipefail {0}
        run: |
          gh secret set ARTIFACTORY_TEST_TOKEN --app actions --body ${{ steps.step1.outputs.access_token }}
          gh secret set ARTIFACTORY_TEST_TOKEN1 --app actions --body ${{ steps.step1.outputs.username_token }}