name: "Rotate Admin JFrog Token"

on:
  schedule:
    - cron: "0 0 30 * *"
  workflow_dispatch:
    inputs:
      EXPIRY_IN_SECONDS:
        type: string
        required: false
        default: "3024000" # 35 days in seconds
        description: Defaults to 85 days. Set it if you are using a different duration.
      JF_PLATFORM_URL:
        type: string
        required: false
        default: "https://artifactory.build.ingka.ikea.com/"
        description: Defaults to current production value. Set it if you are using a different Artifactory setup, like staging.        
        

jobs:
  rotate-jfrog-token-in-gh-secret:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.set-output.outputs.UPDATED_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Make a POST request using curl
        id: step1
        run: |
          response=$(curl "https://artifactory.build.ingka.ikea.com/access/api/v1/tokens" -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_TEST_TOKEN }}" -H "Content-Type: application/json" -X POST -d '{"refreshable": true,"expires_in": 86400 }')
          echo "access_token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV
          echo "Variable set."
      - name: Encode a username&token to Base64
        id: encode-username-token
        run: |
          echo "ARTIFACTORY_TEST_USERNAME : ${{ vars.ARTIFACTORY_TEST_USERNAME }}"
          echo "Access token: $access_token"
          username_token=$(echo -n "${{ vars.ARTIFACTORY_TEST_USERNAME }}:$access_token" | base64)
          echo "username_token:::=$username_token"
          echo "Variable set again."
      - name: Set GitHub Secret
        env:
          NEW_SECRET: "$access_token"  # Replace with your desired secret value
        run: |
          echo "::add-secret::ARTIFACTORY_TEST_TOKEN=${NEW_SECRET}"
          echo "::add-secret::ARTIFACTORY_TEST_TOKEN1=$username_token"
          echo "Secret set successfully"
          echo "ARTIFACTORY_TEST_TOKEN111: ${{ secrets.ARTIFACTORY_TEST_TOKEN }}"  >> $GITHUB_ENV
          echo "ARTIFACTORY_TEST_TOKEN1222: ${{ secrets.ARTIFACTORY_TEST_TOKEN1 }}" >> $GITHUB_ENV
          echo "ARTIFACTORY_TEST_TOKEN111:::=$ARTIFACTORY_TEST_TOKEN111"
          echo "ARTIFACTORY_TEST_TOKEN1222:::=$ARTIFACTORY_TEST_TOKEN1222

