name: "Rotate Admin JFrog Token"

on:
  schedule:
    - cron: "0 0 30 * *"
  workflow_dispatch:
    inputs:
      EXPIRY_IN_SECONDS:
        type: string
        required: false
        default: "3024000" # 35 days in seconds
        description: Defaults to 85 days. Set it if you are using a different duration.
      JF_PLATFORM_URL:
        type: string
        required: false
        default: "https://artifactory.build.ingka.ikea.com/"
        description: Defaults to current production value. Set it if you are using a different Artifactory setup, like staging.        
        

jobs:
  rotate-jfrog-token-in-gh-secret:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.set-output.outputs.UPDATED_ACCESS_TOKEN }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Make a GET request using curl
      run: |
        response=$(curl "https://artifactory.build.ingka.ikea.com/access/api/v1/tokens" -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_TEST_TOKEN }}" -H "Content-Type: application/json" -X POST -d '{"refreshable": true,"expires_in": 86400 }')
        echo "Response from API: $response"